---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  root_password: cm9vdA==
  #root
  username: cm9vdA==
  password: cm9vdA==
  database: cm9vdA==
  #cGV0Y2xpbmlj is root
